# Generated by Django 5.1.1 on 2024-11-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olmsapp', '0003_alter_issuedbookdetails_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='return_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
