# Generated by Django 5.1.1 on 2024-11-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olmsapp', '0004_book_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbookdetails',
            name='fine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
